name: 打包可执行文件

on:
  push:
    branches:
      - op
    paths-ignore: # 这里表示忽略的文件或目录，不会触发流程
      - 'README.md'
      - 'LICENSE'
      - '.gitignore'
      - '.vscode/**'
      - '.test/**'

jobs:
  release:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        node-version: 20
        cache: 'npm'

      - run: npm i
      - run: npm run build:exe

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }}
          path: dist/
          compression-level: 9 # 压缩等级 默认 6

